services:
  health-check:
    build:
      context: .
      dockerfile: Dockerfile-health
      platforms:
        - linux/arm64/v8
        - linux/amd64
    restart: "always"
    depends_on:
      auth:
        condition: service_started
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
      platforms:
        - linux/arm64/v8
        - linux/amd64
    restart: "always"
    ports:
      - "50051:50051"
