name: Build & Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install protoc
        uses: arduino/setup-protoc@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy project files to EC2
        run: |
          sshpass -p '${{ secrets.EC2_PASSWORD }}' scp -o StrictHostKeyChecking=no -r \
            Dockerfile-auth Dockerfile-health docker-compose.yaml proto src Cargo.toml build.rs \
            ubuntu@${{ vars.EC2_IP }}:~/rust-app/

      - name: Deploy on EC2
        run: |
          sshpass -p '${{ secrets.EC2_PASSWORD }}' ssh -o StrictHostKeyChecking=no ubuntu@${{ vars.EC2_IP }} '
            cd ~/rust-app &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          '
